# Generated by Django 5.2.4 on 2026-01-24 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(max_length=255)),
                ('results', models.JSONField(default=list)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='chat.guest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
