# Generated by Django 5.2.4 on 2026-01-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '__first__'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestsearch',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='common.guest'),
        ),
    ]
