# Generated by Django 5.2.4 on 2026-01-25 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('common', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestchat',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='common.guest'),
        ),
    ]
