# Generated by Django 5.2.4 on 2026-01-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_guestchat_guest'),
        ('search', '0002_alter_guestsearch_guest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
