# Generated by Django 5.2.4 on 2026-02-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
